# Generated by Django 5.0.6 on 2024-06-26 22:56
from django.db import migrations


def populate_departments(apps, schema_editor):
    Department = apps.get_model('departments', 'Department')
    Department.objects.create(name='HR')
    Department.objects.create(name='IT')
    Department.objects.create(name='Sales')


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_departments),
    ]
